ARG GO_VERSION

FROM golang:${GO_VERSION}-alpine AS souin

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc libc-dev
ENV GOPATH /app

RUN mkdir -p /app/src/github.com/uaysk/souin-redis
WORKDIR /app/src/github.com/uaysk/souin-redis
ADD ./go.* /app/src/github.com/uaysk/souin-redis/
RUN go mod download
RUN go get golang.org/x/lint/golint
RUN mkdir -p /ssl
ADD ./context /app/src/github.com/uaysk/souin-redis/context
ADD ./pkg /app/src/github.com/uaysk/souin-redis/pkg
ADD ./tests /app/src/github.com/uaysk/souin-redis/tests
ADD ./configuration /app/src/github.com/uaysk/souin-redis/configuration
ADD ./configurationtypes /app/src/github.com/uaysk/souin-redis/configurationtypes
ADD ./helpers /app/src/github.com/uaysk/souin-redis/helpers
ADD ./plugins /app/src/github.com/uaysk/souin-redis/plugins

WORKDIR /app/src/github.com/uaysk/souin-redis

EXPOSE 80

CMD ["go", "run", "plugins/souin/main.go"]
